Add AudioPlayer component
alshakerM/Mente pull request #2
Opened 2022-01-16 14:28 UTC by alshakerM

Added AudioPlayer component.
Changed progressBar to slider from MUI

2022-01-17 13:48 UTC, alshakerM commented
Fix sound lagging.
Added pause icon.
Styled audio timers

2022-01-17 18:24 UTC, alshakero requested changes
Pretty close to perfect. Left some comments.

2022-01-17 18:24 UTC, alshakero commented on components/AudioPlayer/AudioPlayer.js
> +      <div className={styles.playIconContainer}>
This should be a button and the onClick should be on it. 99% of the time it's better for buttons to have onClicks for accessibilty.

2022-01-17 18:24 UTC, alshakero commented on components/AudioPlayer/AudioPlayer.module.css
> +}
I think we should delete every trace of the word "expanded".

2022-01-20 15:12 UTC, alshakerM commented
Delete expanded from audio player.
Added button for onClick to play pause icons

2022-01-24 13:48 UTC, alshakero approved these changes
LGTM. One note.

2022-01-24 13:48 UTC, alshakero commented on components/AudioPlayer/AudioPlayer.js
> +        <button className={styles.playButton}>
The onClick should be on the button.

2022-01-24 14:43 UTC, merged